### ISSUE TITLE
Lots of audio decoding errors

### ISSUE THREAD

**Issue by danieldanielecki** [ourcade/coronavirus-pop-phaser#2]
When running locally the app the screen stops on `Loading...` with many errors in the console (different browsers) mentioning about encoding errors such as `AudioFile.js:91 Error decoding audio: undefined -  Unable to decode audio data` or lack of this asset in the audio cache such as `WebAudioSound.js:48 Uncaught Error: There is no audio asset with key "music-loop" in the audio cache`.

**Comment by supertommy** [comment]
@danieldanielecki try to clone it with git-lfs enabled. The music assets are stored with git-lfs. 

Alternatively you can just download a zip from Github and it will include the .wav files.

Get git-lfs here: https://git-lfs.github.com

**Comment by supertommy** [comment]
@danieldanielecki let me know if that doesn't work for you!

**Comment by danieldanielecki** [comment]
@supertommy thanks for the update of README, `git-lfs clone https://github.com/ourcade/coronavirus-pop-phaser` does works.

However, my `Terminal` warns be `WARNING: 'git lfs clone' is deprecated and will not be updated`. Maybe be careful with using this if it's not being updated anymore. Even though in their [repo](https://github.com/git-lfs/git-lfs) it looks like something is still happening.

**Comment by supertommy** [comment]
@danieldanielecki yes, the `git lfs clone` command is deprecated in favor of simply installing `git-lfs` and using `git clone` as normal. Atlassian has a good article about it: https://www.atlassian.com/git/tutorials/git-lfs

I'm glad it worked for you 👍

**Comment by danieldanielecki** [comment]
@supertommy ohh didn't know, thanks 👍
